import React, { useState, useEffect, useRef } from 'react'
import ReactDOM from 'react-dom'
import { useAlert } from '../../../contexts/AlertContext'
import FloatingInputField from '../../../components/form/FloatingInputField'
import PasswordStrengthIndicator from '../../../components/form/PasswordStrengthIndicator'
import {
	generateStaffAccountAPI,
	getStaffChefListAPI,
	toggleStaffStatusAPI,
	deleteStaffAccountAPI,
} from '../../../services/api/staffAPI'

// Role options - Backend expects 'STAFF' or 'CHEF'
const ROLE_OPTIONS = [
	{ value: 'STAFF', label: 'Waiter', icon: 'restaurant_menu', color: 'text-blue-400' },
	{
		value: 'CHEF',
		label: 'Kitchen Staff',
		icon: 'soup_kitchen',
		color: 'text-orange-400',
	},
]

// Add/Edit Account Modal Component
const AccountModal = ({ isOpen, onClose, onSave, editingAccount }) => {
	const modalRef = useRef(null)
	const [isVisible, setIsVisible] = useState(false)
	const [formData, setFormData] = useState({
		username: '',
		password: '',
		confirmPassword: '',
		role: 'STAFF',
	})
	const [errors, setErrors] = useState({})
	const [saving, setSaving] = useState(false)

	// Track focused field and refs for auto-focus
	const [focusedField, setFocusedField] = useState(null)
	const roleRef = useRef(null)

	useEffect(() => {
		if (isOpen) {
			document.body.style.overflow = 'hidden'
			if (editingAccount) {
				setFormData({
					username: editingAccount.username,
					password: '',
					confirmPassword: '',
					role: editingAccount.role,
				})
			} else {
				setFormData({
					username: '',
					password: '',
					confirmPassword: '',
					role: 'STAFF',
				})
			}
			setErrors({})
			requestAnimationFrame(() => setIsVisible(true))
		} else {
			document.body.style.overflow = 'auto'
			setIsVisible(false)
		}
		return () => {
			document.body.style.overflow = 'auto'
		}
	}, [isOpen, editingAccount])

	// Auto-focus on the last focused field after re-render
	useEffect(() => {
		if (!focusedField) return

		const fieldRefs = {
			role: roleRef,
		}

		const ref = fieldRefs[focusedField]
		if (ref?.current) {
			ref.current.focus()
		}
	}, [formData, errors, focusedField])

	const validateForm = () => {
		const newErrors = {}

		// For staff account creation, username and password are auto-generated by backend
		// Only validate role selection
		if (!formData.role) {
			newErrors.role = 'Please select a role'
		}

		setErrors(newErrors)
		return Object.keys(newErrors).length === 0
	}

	const handleSubmit = async (e) => {
		e.preventDefault()

		if (!validateForm()) return

		setSaving(true)
		try {
			await onSave(formData)
			onClose()
		} catch (error) {
			console.error('Save error:', error)
		} finally {
			setSaving(false)
		}
	}

	const handleChange = (e) => {
		const { name, value } = e.target
		setFocusedField(name) // Track which field is being edited
		setFormData((prev) => ({ ...prev, [name]: value }))
		// Clear error for this field
		if (errors[name]) {
			setErrors((prev) => ({ ...prev, [name]: '' }))
		}
	}

	if (!isOpen) return null

	const ModalContent = () => (
		<div
			className={`fixed inset-0 z-[99999] flex items-center justify-center transition-all duration-300 ${
				isVisible ? 'bg-black/70 backdrop-blur-sm' : 'bg-transparent pointer-events-none'
			}`}
		>
			<div
				ref={modalRef}
				className={`relative bg-[#1A202C] rounded-xl shadow-2xl w-full max-w-md mx-4 border border-white/10 transition-all duration-300 transform ${
					isVisible ? 'scale-100 opacity-100' : 'scale-95 opacity-0'
				}`}
			>
				{/* Header */}
				<div className="flex items-center justify-between p-6 border-b border-white/10">
					<h2 className="text-2xl font-bold text-white m-0">
						{editingAccount ? 'Edit Account' : 'Create New Account'}
					</h2>
					<button
						onClick={onClose}
						className="p-2 rounded-lg text-[#9dabb9] hover:text-white hover:bg-[#2D3748] transition-colors"
					>
						<span className="material-symbols-outlined">close</span>
					</button>
				</div>

				{/* Form */}
				<form onSubmit={handleSubmit} className="p-6 space-y-5">
					{/* Info Message */}
					<div className="bg-blue-500/10 border border-blue-500/30 rounded-lg p-4">
						<p className="text-sm text-blue-300 flex items-center gap-2">
							<span className="material-symbols-outlined text-lg">info</span>
							Username and password will be automatically generated by the system.
						</p>
					</div>

					{/* Role */}
					<div>
						<label className="block text-sm font-medium text-gray-300 mb-2">
							<span className="flex items-center gap-2">
								<span className="material-symbols-outlined text-lg">work</span>
								Role *
							</span>
						</label>
						<div className="relative">
							<select
								ref={roleRef}
								name="role"
								value={formData.role}
								onChange={handleChange}
								onFocus={() => setFocusedField('role')}
								disabled={saving}
								className="w-full px-4 py-2 pl-10 bg-black/40 backdrop-blur-sm border border-white/20 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-[#137fec] transition-all disabled:opacity-50 appearance-none cursor-pointer"
							>
								{ROLE_OPTIONS.map((role) => (
									<option key={role.value} value={role.value}>
										{role.label}
									</option>
								))}
							</select>
							<div className="absolute left-3 top-1/2 -translate-y-1/2 pointer-events-none">
								<span className="material-symbols-outlined text-[#9dabb9]">
									{ROLE_OPTIONS.find((r) => r.value === formData.role)?.icon || 'work'}
								</span>
							</div>
							<div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none">
								<span className="material-symbols-outlined text-[#9dabb9]">
									expand_more
								</span>
							</div>
						</div>
						{errors.role && (
							<p className="text-red-400 text-xs mt-1 flex items-center gap-1">
								<span className="material-symbols-outlined text-sm">error</span>
								{errors.role}
							</p>
						)}
					</div>

					{/* Action Buttons */}
					<div className="flex justify-end gap-3 pt-4">
						<button
							type="button"
							onClick={onClose}
							disabled={saving}
							className="px-4 py-2 rounded-lg bg-[#2D3748] text-white hover:bg-[#4A5568] transition-colors disabled:opacity-50"
						>
							Cancel
						</button>
						<button
							type="submit"
							disabled={saving}
							className="px-6 py-2 rounded-lg bg-[#137fec] text-white font-semibold hover:bg-[#0d6ecc] transition-colors disabled:opacity-50 flex items-center gap-2"
						>
							{saving && (
								<div className="inline-block animate-spin rounded-full h-4 w-4 border-t-2 border-b-2 border-white"></div>
							)}
							{editingAccount ? 'Update Account' : 'Create Account'}
						</button>
					</div>
				</form>
			</div>
		</div>
	)

	return ReactDOM.createPortal(<ModalContent />, document.body)
}

// Account Card Component
const AccountCard = ({ account, onEdit, onToggleActive, onDelete }) => {
	const roleInfo = ROLE_OPTIONS.find((r) => r.value === account.role)
	const [showPassword, setShowPassword] = useState(false)

	return (
		<div className="bg-black/40 backdrop-blur-md rounded-xl border border-white/10 p-5 hover:bg-black/50 transition-all">
			<div className="flex items-start justify-between mb-4">
				<div className="flex items-center gap-3 flex-1">
					<div className="w-12 h-12 rounded-full bg-gradient-to-br from-[#137fec] to-[#0d6ecc] flex items-center justify-center">
						<span className="material-symbols-outlined text-white text-2xl">
							{roleInfo?.icon}
						</span>
					</div>
					<div className="flex-1">
						<h3 className="text-white font-bold text-lg m-0">{account.username}</h3>
						{account.generatedPassword && (
							<div className="mt-1 px-2 py-1 bg-yellow-500/20 border border-yellow-500/50 rounded text-xs text-yellow-300 flex items-center justify-between gap-2">
								<div className="flex items-center gap-1">
									<span className="font-semibold">Password:</span>
									<span className="font-mono">
										{showPassword ? account.generatedPassword : '••••••••'}
									</span>
								</div>
								<button
									onClick={(e) => {
										e.stopPropagation()
										setShowPassword(!showPassword)
									}}
									className="p-0.5 hover:bg-yellow-500/30 rounded transition-colors"
									title={showPassword ? 'Hide password' : 'Show password'}
								>
									<span className="material-symbols-outlined text-sm">
										{showPassword ? 'visibility_off' : 'visibility'}
									</span>
								</button>
							</div>
						)}
						<div className="flex items-center gap-2 mt-1">
							<span
								className={`text-sm font-medium ${roleInfo?.color || 'text-gray-400'}`}
							>
								{roleInfo?.label}
							</span>
							<span className="text-[#9dabb9] text-xs">•</span>
							<span
								className={`text-xs px-2 py-0.5 rounded-full ${
									account.isActive
										? 'bg-green-500/20 text-green-400'
										: 'bg-gray-500/20 text-gray-400'
								}`}
							>
								{account.isActive ? 'Active' : 'Disabled'}
							</span>
						</div>
					</div>
				</div>
			</div>

			<div className="flex items-center justify-between pt-3 border-t border-white/10">
				<span className="text-xs text-[#9dabb9]">
					Created: {new Date(account.createdAt).toLocaleDateString()}
				</span>

				<div className="flex items-center gap-2">
					<button
						onClick={() => onToggleActive(account)}
						className={`p-2 rounded-lg transition-colors ${
							account.isActive
								? 'bg-yellow-500/20 text-yellow-400 hover:bg-yellow-500/30'
								: 'bg-green-500/20 text-green-400 hover:bg-green-500/30'
						}`}
						title={account.isActive ? 'Disable' : 'Enable'}
					>
						<span className="material-symbols-outlined text-lg">
							{account.isActive ? 'block' : 'check_circle'}
						</span>
					</button>
					<button
						onClick={() => onDelete(account)}
						className="p-2 rounded-lg bg-red-500/20 text-red-400 hover:bg-red-500/30 transition-colors"
						title="Delete"
					>
						<span className="material-symbols-outlined text-lg">delete</span>
					</button>
				</div>
			</div>
		</div>
	)
}

// Main Account Management Component
const AccountManagement = () => {
	const { showSuccess, showError, showConfirm } = useAlert()
	const [accounts, setAccounts] = useState([])
	const [loading, setLoading] = useState(true)
	const [fetchError, setFetchError] = useState(false)
	const [isModalOpen, setIsModalOpen] = useState(false)
	const [editingAccount, setEditingAccount] = useState(null)
	const [searchQuery, setSearchQuery] = useState('')
	const [roleFilter, setRoleFilter] = useState('ALL')

	const fetchAccounts = async (retryCount = 0) => {
		const MAX_RETRIES = 3
		const RETRY_DELAY = 1000 // 1 second

		setLoading(true)
		setFetchError(false)
		try {
			console.log(
				`🔄 Fetching staff accounts... (Attempt ${retryCount + 1}/${MAX_RETRIES + 1})`,
			)
			const result = await getStaffChefListAPI()

			if (result.success) {
				// Transform API data to match component format
				const transformedAccounts = result.data.items.map((user) => {
					// Extract role from user.roles array
					const roleObj = user.roles?.find((r) => r.name === 'STAFF' || r.name === 'CHEF')
					const role = roleObj?.name || 'STAFF'

					return {
						id: user.userId,
						username: user.username,
						role: role,
						isActive: user.isActive ?? true,
						createdAt: new Date().toISOString(), // API doesn't return createdAt yet
					}
				})

				console.log('✅ Fetched accounts:', transformedAccounts)
				setAccounts(transformedAccounts)
				setFetchError(false)
			} else {
				console.error('❌ Failed to fetch accounts:', result.message)
				// Retry logic
				if (retryCount < MAX_RETRIES) {
					console.log(`⏳ Retrying in ${RETRY_DELAY / 1000}s...`)
					await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY))
					return fetchAccounts(retryCount + 1)
				}
				setFetchError(true)
				showError(result.message || 'Failed to load staff accounts. Please try again.')
				setAccounts([])
			}
		} catch (error) {
			console.error('❌ fetchAccounts error:', error)
			// Retry logic
			if (retryCount < MAX_RETRIES) {
				console.log(`⏳ Retrying in ${RETRY_DELAY / 1000}s...`)
				await new Promise((resolve) => setTimeout(resolve, RETRY_DELAY))
				return fetchAccounts(retryCount + 1)
			}
			setFetchError(true)
			showError('Failed to load staff accounts. Please try again.')
			setAccounts([])
		} finally {
			setLoading(false)
		}
	}

	// Load accounts on mount only
	useEffect(() => {
		// eslint-disable-next-line @typescript-eslint/no-floating-promises
		fetchAccounts()
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [])

	const handleCreateAccount = () => {
		setEditingAccount(null)
		setIsModalOpen(true)
	}

	const handleEditAccount = (account) => {
		setEditingAccount(account)
		setIsModalOpen(true)
	}

	const handleSaveAccount = async (formData) => {
		try {
			if (editingAccount) {
				// Update existing account - NOT IMPLEMENTED YET
				showError('Update feature is not implemented yet. Please contact administrator.')
				return
			} else {
				// Create new account via API
				console.log('🔄 Calling generateStaffAccountAPI with role:', formData.role)
				const result = await generateStaffAccountAPI(formData.role)
				console.log('📦 API Response:', result)

				if (result.success) {
					// Add to local state
					const newAccount = {
						id: result.data.userId,
						username: result.data.username,
						role: result.data.role,
						isActive: true,
						createdAt: new Date().toISOString(),
						generatedPassword: result.data.password, // Store temporarily for display
					}
					console.log('✅ Creating account:', newAccount)
					setAccounts((prev) => [newAccount, ...prev])

					// Show success with credentials
					showSuccess(
						`Account created successfully!\n\nUsername: ${result.data.username}\nPassword: ${result.data.password}\n\nPlease save these credentials!`,
						10000, // Show for 10 seconds
					)
				} else {
					console.error('❌ API failed:', result.message)
					showError(result.message || 'Failed to create account')
				}
			}
		} catch (error) {
			console.error('❌ Save account error:', error)
			showError('Failed to save account. Please try again.')
		}
	}

	const handleToggleActive = async (account) => {
		const action = account.isActive ? 'disable' : 'enable'
		const confirmed = await showConfirm(
			`${action.charAt(0).toUpperCase() + action.slice(1)} Account`,
			`Are you sure you want to ${action} "${account.username}"?`,
		)

		if (confirmed) {
			try {
				console.log(`${action} account:`, account.id)
				const result = await toggleStaffStatusAPI(account.id, !account.isActive)

				if (result.success) {
					// Update local state
					setAccounts((prev) =>
						prev.map((acc) =>
							acc.id === account.id ? { ...acc, isActive: !acc.isActive } : acc,
						),
					)
					showSuccess(`Account "${account.username}" ${action}d successfully!`)
				} else {
					showError(result.message || `Failed to ${action} account`)
				}
			} catch (error) {
				console.error(`Error ${action}ing account:`, error)
				showError(`Failed to ${action} account`)
			}
		}
	}

	const handleDeleteAccount = async (account) => {
		const confirmed = await showConfirm(
			'Delete Account',
			`Are you sure you want to delete "${account.username}"? This action cannot be undone.`,
		)

		if (confirmed) {
			try {
				console.log('Deleting account:', account.id)
				const result = await deleteStaffAccountAPI(account.id)

				if (result.success) {
					// Remove from local state
					setAccounts((prev) => prev.filter((acc) => acc.id !== account.id))
					showSuccess(`Account "${account.username}" deleted successfully!`)
				} else {
					showError(result.message || 'Failed to delete account')
				}
			} catch (error) {
				console.error('Error deleting account:', error)
				showError('Failed to delete account')
			}
		}
	}

	// Filter accounts
	const filteredAccounts = accounts.filter((account) => {
		const matchesSearch = account.username
			.toLowerCase()
			.includes(searchQuery.toLowerCase())
		const matchesRole = roleFilter === 'ALL' || account.role === roleFilter
		return matchesSearch && matchesRole
	})

	return (
		<div className="settings-card bg-black/40 backdrop-blur-md rounded-xl border border-white/10">
			{/* Header */}
			<div className="card-header p-6 border-b border-white/10">
				<div className="flex items-center justify-between">
					<div>
						<h2 className="text-xl font-bold text-white m-0 flex items-center gap-2">
							<span className="material-symbols-outlined">manage_accounts</span>
							Staff Account Management
						</h2>
						<p className="text-sm text-gray-300 mt-1">
							Create and manage staff accounts for waiters and kitchen staff.
						</p>
					</div>
					<button
						onClick={handleCreateAccount}
						className="px-4 py-2 bg-[#137fec] hover:bg-[#0d6ecc] text-white rounded-lg font-semibold transition-colors flex items-center gap-2"
					>
						<span className="material-symbols-outlined">add</span>
						Create Account
					</button>
				</div>
			</div>

			{/* Filters */}
			<div className="p-6 border-b border-white/10">
				<div className="flex gap-4">
					<div className="flex-1">
						<input
							type="text"
							value={searchQuery}
							onChange={(e) => setSearchQuery(e.target.value)}
							placeholder="Search by username..."
							className="w-full px-4 py-2 bg-black/40 backdrop-blur-sm border border-white/20 rounded-lg text-white placeholder-[#9dabb9] focus:outline-none focus:ring-2 focus:ring-[#137fec] transition-all"
						/>
					</div>
					<div className="relative min-w-[180px]">
						<select
							value={roleFilter}
							onChange={(e) => setRoleFilter(e.target.value)}
							className="w-full px-4 py-2 bg-black/40 backdrop-blur-sm border border-white/20 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-[#137fec] transition-all appearance-none cursor-pointer"
						>
							<option value="ALL">All Roles</option>
							{ROLE_OPTIONS.map((role) => (
								<option key={role.value} value={role.value}>
									{role.label}
								</option>
							))}
						</select>
						<div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none">
							<span className="material-symbols-outlined text-[#9dabb9]">
								expand_more
							</span>
						</div>
					</div>
				</div>
			</div>

			{/* Account List */}
			<div className="p-6">
				{loading ? (
					<div className="text-center py-12">
						<div className="inline-block animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-[#137fec] mb-4"></div>
						<p className="text-[#9dabb9]">Loading accounts...</p>
					</div>
				) : fetchError ? (
					<div className="text-center py-12">
						<span className="material-symbols-outlined text-6xl text-red-400 mb-4 block">
							error
						</span>
						<p className="text-red-400 text-lg font-semibold mb-2">
							Failed to load accounts
						</p>
						<p className="text-[#9dabb9] mb-4">
							Unable to fetch staff accounts. Please try again.
						</p>
						<button
							onClick={() => fetchAccounts()}
							className="px-6 py-2 bg-[#137fec] hover:bg-[#0d6ecc] text-white rounded-lg font-semibold transition-colors flex items-center gap-2 mx-auto"
						>
							<span className="material-symbols-outlined">refresh</span>
							Retry
						</button>
					</div>
				) : filteredAccounts.length > 0 ? (
					<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
						{filteredAccounts.map((account) => (
							<AccountCard
								key={account.id}
								account={account}
								onEdit={handleEditAccount}
								onToggleActive={handleToggleActive}
								onDelete={handleDeleteAccount}
							/>
						))}
					</div>
				) : (
					<div className="text-center py-12">
						<span className="material-symbols-outlined text-6xl text-[#9dabb9] mb-4 block">
							person_off
						</span>
						<p className="text-[#9dabb9] text-lg">
							{searchQuery || roleFilter !== 'ALL'
								? 'No accounts found matching your filters.'
								: 'No accounts yet. Create your first staff account!'}
						</p>
					</div>
				)}
			</div>

			{/* Modal */}
			<AccountModal
				isOpen={isModalOpen}
				onClose={() => {
					setIsModalOpen(false)
					setEditingAccount(null)
				}}
				onSave={handleSaveAccount}
				editingAccount={editingAccount}
			/>
		</div>
	)
}

export default AccountManagement
